/**
 * GENERATED by scripts/fetch-gallery.mjs — do not edit by hand.
 * Source list: scripts/gallery-list.mjs · credits: public/gallery/CREDITS.md
 * Every work is public domain / CC0 (licence re-checked from Commons at build time).
 */
export type ArtworkKind =
  | "art" | "film" | "book" | "quote" | "essay" | "culture" | "story" | "word" | "history" | "news";

export interface Artwork {
  id: string;
  title: string;
  artist: string;
  year: string;
  museum: string;
  /** Commons file page — the credit link. */
  source: string;
  licence: string;
  /** Candidate for the hero art wall. */
  wall: boolean;
  kind: ArtworkKind | null;
  /** Resting tilt on the paper desk, degrees (ignored in the dark gallery). */
  tilt: number;
  /** Average colour, for blurred backdrops and placeholders. */
  dominant: string;
  w640: number;
  h640: number;
  w1400: number;
  h1400: number;
}

export const GALLERY: readonly Artwork[] = [
  { id: "starry-night", title: "The Starry Night", artist: "Vincent van Gogh", year: "1889", museum: "Museum of Modern Art",
    source: "https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", licence: "Public domain", wall: true, kind: "art", tilt: -2,
    dominant: "#181818", w640: 640, h640: 507, w1400: 1400, h1400: 1108 },
  { id: "almond-blossom", title: "Almond Blossom", artist: "Vincent van Gogh", year: "1890", museum: "Van Gogh Museum",
    source: "https://commons.wikimedia.org/wiki/File:Amandelbloesem_-_s0176V1962_-_Van_Gogh_Museum.jpg", licence: "Public domain", wall: true, kind: "story", tilt: 1.5,
    dominant: "#389898", w640: 640, h640: 505, w1400: 1400, h1400: 1106 },
  { id: "wheatfield-crows", title: "Wheatfield with Crows", artist: "Vincent van Gogh", year: "1890", museum: "Van Gogh Museum",
    source: "https://commons.wikimedia.org/wiki/File:Korenveld_met_kraaien_-_s0149V1962_-_Van_Gogh_Museum.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#c8a808", w640: 640, h640: 307, w1400: 1400, h1400: 671 },
  { id: "cafe-terrace", title: "Café Terrace at Night", artist: "Vincent van Gogh", year: "1888", museum: "Kröller-Müller Museum",
    source: "https://commons.wikimedia.org/wiki/File:Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_(Yorck).jpg", licence: "Public domain", wall: true, kind: null, tilt: -1.5,
    dominant: "#282828", w640: 510, h640: 640, w1400: 1116, h1400: 1400 },
  { id: "bedroom", title: "The Bedroom", artist: "Vincent van Gogh", year: "1888", museum: "Van Gogh Museum",
    source: "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#987848", w640: 640, h640: 507, w1400: 1400, h1400: 1111 },
  { id: "sunflowers", title: "Sunflowers", artist: "Vincent van Gogh", year: "1888", museum: "National Gallery, London",
    source: "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Sunflowers_(1888%2C_National_Gallery_London).jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#d8c878", w640: 504, h640: 640, w1400: 1101, h1400: 1400 },
  { id: "the-kiss", title: "The Kiss", artist: "Gustav Klimt", year: "1907", museum: "Belvedere",
    source: "https://commons.wikimedia.org/wiki/File:The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg", licence: "Public domain", wall: true, kind: null, tilt: 2,
    dominant: "#887848", w640: 638, h640: 640, w1400: 1395, h1400: 1400 },
  { id: "adele-bloch-bauer", title: "Portrait of Adele Bloch-Bauer I", artist: "Gustav Klimt", year: "1907", museum: "Neue Galerie New York",
    source: "https://commons.wikimedia.org/wiki/File:Gustav_Klimt_-_Portr%C3%A4t_der_Adele_Bloch-Bauer_I_(1907).jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#a87818", w640: 640, h640: 640, w1400: 1400, h1400: 1400 },
  { id: "milkmaid", title: "The Milkmaid", artist: "Johannes Vermeer", year: "1660", museum: "Rijksmuseum",
    source: "https://commons.wikimedia.org/wiki/File:Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg", licence: "Public domain", wall: true, kind: null, tilt: -1,
    dominant: "#d8d8c8", w640: 571, h640: 640, w1400: 1248, h1400: 1400 },
  { id: "woman-reading-letter", title: "Woman Reading a Letter", artist: "Johannes Vermeer", year: "c. 1663", museum: "Rijksmuseum",
    source: "https://commons.wikimedia.org/wiki/File:Brieflezende_vrouw%2C_SK-C-251.jpg", licence: "CC0", wall: false, kind: "book", tilt: -1.1,
    dominant: "#484828", w640: 536, h640: 640, w1400: 1172, h1400: 1400 },
  { id: "girl-pearl-earring", title: "Girl with a Pearl Earring", artist: "Johannes Vermeer", year: "c. 1665", museum: "Mauritshuis",
    source: "https://commons.wikimedia.org/wiki/File:1665_Girl_with_a_Pearl_Earring.jpg", licence: "Public domain", wall: true, kind: null, tilt: 1,
    dominant: "#282818", w640: 540, h640: 640, w1400: 1182, h1400: 1400 },
  { id: "night-watch", title: "The Night Watch", artist: "Rembrandt", year: "1642", museum: "Rijksmuseum",
    source: "https://commons.wikimedia.org/wiki/File:La_ronda_de_noche%2C_por_Rembrandt_van_Rijn.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#181808", w640: 640, h640: 521, w1400: 1400, h1400: 1139 },
  { id: "winter-skaters", title: "Winter landscape with skaters", artist: "Hendrick Avercamp", year: "1608", museum: "Rijksmuseum",
    source: "https://commons.wikimedia.org/wiki/File:Hendrick_Avercamp_-_Winterlandschap_met_ijsvermaak.jpg", licence: "Public domain", wall: false, kind: "culture", tilt: -1.1,
    dominant: "#b8b898", w640: 640, h640: 369, w1400: 1400, h1400: 809 },
  { id: "birth-of-venus", title: "The Birth of Venus", artist: "Sandro Botticelli", year: "1485", museum: "Uffizi Gallery",
    source: "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg", licence: "Public domain", wall: true, kind: null, tilt: 1.5,
    dominant: "#282818", w640: 640, h640: 402, w1400: 1400, h1400: 879 },
  { id: "primavera", title: "Primavera", artist: "Sandro Botticelli", year: "1480", museum: "Uffizi Gallery",
    source: "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_Primavera_-_Google_Art_Project.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#181818", w640: 640, h640: 425, w1400: 1400, h1400: 930 },
  { id: "arnolfini", title: "Arnolfini Portrait", artist: "Jan van Eyck", year: "1434", museum: "National Gallery, London",
    source: "https://commons.wikimedia.org/wiki/File:Van_Eyck_-_Arnolfini_Portrait.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#181818", w640: 468, h640: 640, w1400: 1023, h1400: 1400 },
  { id: "hunters-in-snow", title: "The Hunters in the Snow", artist: "Pieter Brueghel the Elder", year: "1565", museum: "Kunsthistorisches Museum",
    source: "https://commons.wikimedia.org/wiki/File:Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_(Winter)_-_Google_Art_Project.jpg", licence: "Public domain", wall: false, kind: "history", tilt: -1.1,
    dominant: "#687858", w640: 640, h640: 455, w1400: 1400, h1400: 996 },
  { id: "tower-of-babel", title: "The Tower of Babel", artist: "Pieter Brueghel the Elder", year: "1563", museum: "Kunsthistorisches Museum",
    source: "https://commons.wikimedia.org/wiki/File:Pieter_Bruegel_d._%C3%84.%2C_Kunsthistorisches_Museum_Wien%2C_Gem%C3%A4ldegalerie_-_Turmbau_zu_Babel_-_GG_1026_-_Kunsthistorisches_Museum.jpg", licence: "Public domain", wall: false, kind: "culture", tilt: -1.1,
    dominant: "#b8b8a8", w640: 640, h640: 471, w1400: 1400, h1400: 1031 },
  { id: "las-meninas", title: "Las Meninas", artist: "Diego Velázquez", year: "1656", museum: "Museo del Prado",
    source: "https://commons.wikimedia.org/wiki/File:Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#080808", w640: 556, h640: 640, w1400: 1216, h1400: 1400 },
  { id: "school-of-athens", title: "The School of Athens", artist: "Raphael", year: "1509–1511", museum: "Vatican Museums",
    source: "https://commons.wikimedia.org/wiki/File:The_School_of_Athens_by_Raffaello_Sanzio_da_Urbino.jpg", licence: "Public domain", wall: false, kind: "essay", tilt: -1.1,
    dominant: "#988878", w640: 640, h640: 446, w1400: 1400, h1400: 976 },
  { id: "dante-michelino", title: "Dante and the Three Kingdoms", artist: "Domenico di Michelino", year: "1465", museum: "Florence Cathedral",
    source: "https://commons.wikimedia.org/wiki/File:Domenico-Di-Michelino-Dante-and-the-Three-Kingdoms.jpg", licence: "CC0", wall: false, kind: "book", tilt: -1.1,
    dominant: "#685848", w640: 640, h640: 502, w1400: 1400, h1400: 1098 },
  { id: "young-girl-reading", title: "A Young Girl Reading", artist: "Jean-Honoré Fragonard", year: "1770", museum: "National Gallery of Art",
    source: "https://commons.wikimedia.org/wiki/File:Fragonard%2C_The_Reader.jpg", licence: "Public domain", wall: true, kind: "word", tilt: -1.5,
    dominant: "#483828", w640: 509, h640: 640, w1400: 1114, h1400: 1400 },
  { id: "vigee-straw-hat", title: "Self Portrait in a Straw Hat", artist: "Élisabeth Louise Vigée Le Brun", year: "1782", museum: "National Gallery, London",
    source: "https://commons.wikimedia.org/wiki/File:Self-portrait_in_a_Straw_Hat_by_Elisabeth-Louise_Vig%C3%A9e-Lebrun.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#181818", w640: 461, h640: 640, w1400: 1008, h1400: 1400 },
  { id: "labille-guiard-pupils", title: "Self-Portrait with Two Pupils", artist: "Adélaïde Labille-Guiard", year: "1785", museum: "Metropolitan Museum of Art",
    source: "https://commons.wikimedia.org/wiki/File:Ad%C3%A9la%C3%AFde_Labille-Guiard_-_Self-Portrait_with_Two_Pupils_-_The_Metropolitan_Museum_of_Art.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#282818", w640: 447, h640: 640, w1400: 977, h1400: 1400 },
  { id: "wanderer-fog", title: "Wanderer above the Sea of Fog", artist: "Caspar David Friedrich", year: "c. 1818", museum: "Hamburger Kunsthalle",
    source: "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg", licence: "Public domain", wall: true, kind: null, tilt: 1,
    dominant: "#181818", w640: 500, h640: 640, w1400: 1093, h1400: 1400 },
  { id: "fighting-temeraire", title: "The Fighting Temeraire", artist: "J. M. W. Turner", year: "1839", museum: "National Gallery, London",
    source: "https://commons.wikimedia.org/wiki/File:Turner%2C_J._M._W._-_The_Fighting_T%C3%A9m%C3%A9raire_tugged_to_her_last_Berth_to_be_broken.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#b89878", w640: 640, h640: 475, w1400: 1400, h1400: 1040 },
  { id: "liberty-leading", title: "Liberty Leading the People", artist: "Eugène Delacroix", year: "1830", museum: "Musée du Louvre",
    source: "https://commons.wikimedia.org/wiki/File:Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg", licence: "Public domain", wall: false, kind: "history", tilt: -1.1,
    dominant: "#181818", w640: 640, h640: 507, w1400: 1400, h1400: 1108 },
  { id: "ophelia", title: "Ophelia", artist: "John Everett Millais", year: "1851", museum: "Tate",
    source: "https://commons.wikimedia.org/wiki/File:John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#f8f8f8", w640: 640, h640: 435, w1400: 1400, h1400: 952 },
  { id: "lady-of-shalott", title: "The Lady of Shalott", artist: "John William Waterhouse", year: "1888", museum: "Tate",
    source: "https://commons.wikimedia.org/wiki/File:John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project_(derivative_work_-_AutoContrast_edit_in_LCH_space).jpg", licence: "Public domain", wall: false, kind: "quote", tilt: -1.1,
    dominant: "#181818", w640: 640, h640: 491, w1400: 1400, h1400: 1075 },
  { id: "horse-fair", title: "The Horse Fair", artist: "Rosa Bonheur", year: "1853", museum: "Metropolitan Museum of Art",
    source: "https://commons.wikimedia.org/wiki/File:Rosa_Bonheur%2C_The_Horse_Fair%2C_1852%E2%80%9355.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#383828", w640: 640, h640: 303, w1400: 1400, h1400: 663 },
  { id: "moulin-galette", title: "Bal du moulin de la Galette", artist: "Pierre-Auguste Renoir", year: "1876", museum: "Musée d'Orsay",
    source: "https://commons.wikimedia.org/wiki/File:Renoir%2C_Pierre-Auguste_-_Dance_at_Le_Moulin_de_la_Galette%2C_1876.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#080808", w640: 640, h640: 475, w1400: 1400, h1400: 1041 },
  { id: "woman-parasol", title: "Woman with a Parasol – Madame Monet and Her Son", artist: "Claude Monet", year: "1886", museum: "National Gallery of Art",
    source: "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg", licence: "Public domain", wall: true, kind: null, tilt: -2,
    dominant: "#687888", w640: 515, h640: 640, w1400: 1127, h1400: 1400 },
  { id: "impression-sunrise", title: "Impression, Sunrise", artist: "Claude Monet", year: "1872", museum: "Musée Marmottan Monet",
    source: "https://commons.wikimedia.org/wiki/File:Monet_-_Impression%2C_Sunrise.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#888878", w640: 640, h640: 496, w1400: 1400, h1400: 1086 },
  { id: "paris-rainy-day", title: "Paris Street; Rainy Day", artist: "Gustave Caillebotte", year: "1877", museum: "Art Institute of Chicago",
    source: "https://commons.wikimedia.org/wiki/File:Gustave_Caillebotte_-_Paris_Street%2C_Rainy_Day_-_1964.336_-_Art_Institute_of_Chicago.jpg", licence: "Public domain", wall: false, kind: "news", tilt: -1.1,
    dominant: "#a8a898", w640: 640, h640: 497, w1400: 1400, h1400: 1087 },
  { id: "dance-class", title: "The Dance Class", artist: "Edgar Degas", year: "1874", museum: "Metropolitan Museum of Art",
    source: "https://commons.wikimedia.org/wiki/File:Edgar_Degas_The_Dance_Class.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#687858", w640: 592, h640: 640, w1400: 1295, h1400: 1400 },
  { id: "grande-jatte", title: "A Sunday Afternoon on the Island of La Grande Jatte", artist: "Georges Seurat", year: "1884", museum: "Art Institute of Chicago",
    source: "https://commons.wikimedia.org/wiki/File:A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg", licence: "Public domain", wall: true, kind: null, tilt: 1.5,
    dominant: "#384848", w640: 640, h640: 426, w1400: 1400, h1400: 932 },
  { id: "the-cradle", title: "The Cradle", artist: "Berthe Morisot", year: "1872", museum: "Musée d'Orsay",
    source: "https://commons.wikimedia.org/wiki/File:Berthe_Morisot_-_The_Cradle_-_Google_Art_Project.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#c8b8a8", w640: 526, h640: 640, w1400: 1149, h1400: 1400 },
  { id: "childs-bath", title: "The Child's Bath", artist: "Mary Cassatt", year: "1893", museum: "Art Institute of Chicago",
    source: "https://commons.wikimedia.org/wiki/File:The_Child's_Bath_by_Mary_Cassatt_1893.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#585848", w640: 419, h640: 640, w1400: 918, h1400: 1400 },
  { id: "boulevard-montmartre-night", title: "The Boulevard Montmartre at Night", artist: "Camille Pissarro", year: "1897", museum: "National Gallery, London",
    source: "https://commons.wikimedia.org/wiki/File:Camille_Pissarro_-_Boulevard_Montmartre_at_Night_-_c_1897_-_National_Gallery_UK.jpg", licence: "Public domain", wall: false, kind: "news", tilt: -1.1,
    dominant: "#283848", w640: 640, h640: 526, w1400: 1400, h1400: 1151 },
  { id: "mont-sainte-victoire", title: "Mont Sainte-Victoire and the Viaduct of the Arc River Valley", artist: "Paul Cézanne", year: "1882", museum: "Metropolitan Museum of Art",
    source: "https://commons.wikimedia.org/wiki/File:Paul_C%C3%A9zanne_-_Mont_Sainte-Victoire_and_the_Viaduct_of_the_Arc_River_Valley_(Metropolitan_Museum_of_Art).jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#a8a898", w640: 640, h640: 518, w1400: 1400, h1400: 1134 },
  { id: "rousseau-dream", title: "The Dream", artist: "Henri Rousseau", year: "1910", museum: "Museum of Modern Art",
    source: "https://commons.wikimedia.org/wiki/File:Henri_Rousseau_005.jpg", licence: "Public domain", wall: true, kind: null, tilt: -1,
    dominant: "#283828", w640: 640, h640: 433, w1400: 1400, h1400: 948 },
  { id: "rousseau-tiger", title: "Tiger in a Tropical Storm", artist: "Henri Rousseau", year: "1891", museum: "National Gallery, London",
    source: "https://commons.wikimedia.org/wiki/File:Surprised-Rousseau.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#282818", w640: 640, h640: 511, w1400: 1400, h1400: 1119 },
  { id: "great-wave", title: "Under the Wave off Kanagawa (The Great Wave)", artist: "Katsushika Hokusai", year: "c. 1830–32", museum: "The Metropolitan Museum of Art",
    source: "https://commons.wikimedia.org/wiki/File:%E3%80%8C%E5%AF%8C%E5%B6%BD%E4%B8%89%E5%8D%81%E5%85%AD%E6%99%AF_%E7%A5%9E%E5%A5%88%E5%B7%9D%E6%B2%96%E6%B5%AA%E8%A3%8F%E3%80%8D-Under_the_Wave_off_Kanagawa_(Kanagawa_oki_nami_ura)%2C_or_The_Great_Wave%2C_from_the_series_Thirty-six_Views_of_Mount_Fuji_(Fugaku_sanj%C5%ABrokkei)_MET_DP141042.jpg", licence: "CC0", wall: true, kind: "culture", tilt: -1.5,
    dominant: "#e8d8b8", w640: 640, h640: 437, w1400: 1400, h1400: 957 },
  { id: "the-scream", title: "The Scream", artist: "Edvard Munch", year: "1893", museum: "National Museum, Oslo",
    source: "https://commons.wikimedia.org/wiki/File:Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#786858", w640: 516, h640: 640, w1400: 1128, h1400: 1400 },
  { id: "composition-viii", title: "Composition VIII", artist: "Wassily Kandinsky", year: "1923", museum: "Solomon R. Guggenheim Museum",
    source: "https://commons.wikimedia.org/wiki/File:Kandinsky_-_Composition_8%2C_July_1923.jpg", licence: "CC0", wall: false, kind: null, tilt: -1.1,
    dominant: "#d8c8b8", w640: 640, h640: 466, w1400: 1400, h1400: 1020 },
  { id: "yellow-cow", title: "The Yellow Cow", artist: "Franz Marc", year: "1911", museum: "Solomon R. Guggenheim Museum",
    source: "https://commons.wikimedia.org/wiki/File:Franz_Marc-The_Yellow_Cow-1911.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#080808", w640: 640, h640: 478, w1400: 1067, h1400: 797 },
  { id: "af-klint-ten-largest-7", title: "The Ten Largest, No. 7, Adulthood", artist: "Hilma af Klint", year: "1907", museum: "Hilma af Klint Foundation",
    source: "https://commons.wikimedia.org/wiki/File:Hilma_af_Klint_-_The_Ten_Largest_No._7_-_Adulthood_-_1907.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#b89898", w640: 482, h640: 640, w1400: 1055, h1400: 1400 },
  { id: "harmony-in-red", title: "The Dessert: Harmony in Red (The Red Room)", artist: "Henri Matisse", year: "1907", museum: "State Hermitage Museum",
    source: "https://commons.wikimedia.org/wiki/File:La_Desserte_rouge%2C_par_Henri_Matisse.jpg", licence: "Public domain", wall: false, kind: null, tilt: -1.1,
    dominant: "#980828", w640: 640, h640: 528, w1400: 1400, h1400: 1155 },
  { id: "proust-portrait", title: "Portrait de Marcel Proust", artist: "Jacques-Émile Blanche", year: "1892", museum: "Musée d'Orsay",
    source: "https://commons.wikimedia.org/wiki/File:Jacques-Emile_Blanche_Portrait_de_Marcel_Proust_1892.jpg", licence: "Public domain", wall: false, kind: "quote", tilt: -1.1,
    dominant: "#181818", w640: 526, h640: 640, w1400: 887, h1400: 1080 },
  { id: "great-train-robbery", title: "The Great Train Robbery (film still)", artist: "Edwin S. Porter", year: "1903", museum: "Edison Manufacturing Company",
    source: "https://commons.wikimedia.org/wiki/File:Great_train_robbery_still.jpg", licence: "Public domain", wall: false, kind: "film", tilt: -1.1,
    dominant: "#786858", w640: 489, h640: 405, w1400: 489, h1400: 405 },
] as const;

export const artworkById = (id: string): Artwork => {
  const a = GALLERY.find((g) => g.id === id);
  if (!a) throw new Error(`Unknown artwork: ${id}`);
  return a;
};

/** "Artist, Title (year)" — the alt text every artwork carries. */
export const artworkAlt = (a: Artwork) => `${a.artist}, ${a.title} (${a.year})`;

export const artworkSrc = (a: Artwork, size: 640 | 1400 = 640) => `/gallery/${a.id}-${size}.webp`;

export const artworkSrcSet = (a: Artwork) =>
  `/gallery/${a.id}-640.webp ${a.w640}w, /gallery/${a.id}-1400.webp ${a.w1400}w`;
