/**
 * GENERATED by scripts/fetch-library-covers.mjs — do not edit by hand.
 * The app's Library, as shown on the homepage shelf: Standard Ebooks titles
 * (public-domain text; covers CC0), every chapter rewritten at six levels.
 */
export interface LibraryBook {
  id: string;
  title: string;
  author: string;
  year: string;
  chapters: number;
  width: number;
  height: number;
}

export const LIBRARY: readonly LibraryBook[] = [
  { id: "notes-from-underground", title: "Notes from Underground", author: "Fyodor Dostoevsky", year: "1864", chapters: 21, width: 480, height: 720 },
  { id: "alice", title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", year: "1865", chapters: 12, width: 480, height: 720 },
  { id: "washington-square", title: "Washington Square", author: "Henry James", year: "1880", chapters: 35, width: 480, height: 720 },
  { id: "pierre-and-jean", title: "Pierre and Jean", author: "Guy de Maupassant", year: "1888", chapters: 9, width: 480, height: 720 },
  { id: "call-of-the-wild", title: "The Call of the Wild", author: "Jack London", year: "1903", chapters: 7, width: 480, height: 720 },
  { id: "gatsby", title: "The Great Gatsby", author: "F. Scott Fitzgerald", year: "1925", chapters: 9, width: 480, height: 720 },
] as const;

export const bookCoverSrc = (b: LibraryBook) => `/library/${b.id}.webp`;
