import type { LegalLang } from "@/lib/legal";

/**
 * The story — Mustafa's own letter (rewritten 2026-09-19), in seven
 * languages. A sequence of blocks rather than fixed paragraphs, so the page
 * can set each kind differently: paragraphs (with `==…==` marking the one
 * phrase the highlighter draws under), the three "phrasebook" lines, the
 * three epigraphs, the clippings, and the closing lines.
 *
 * Translations were written to read as if first written in each language
 * (idiom over word order); the three quotations use the established wording
 * in each language (the French text keeps Proust's and Van Gogh's originals).
 */
export type StoryBlock =
  | { type: "p"; text: string }
  | { type: "lines"; lines: string[] }
  | { type: "quote"; text: string; cite: string }
  | { type: "art"; slot: number; caption: string }
  | { type: "finale"; lines: string[] };

export interface StoryCopy {
  title: string;
  intro: string;
  blocks: StoryBlock[];
  signoff: string;
  /** The small invitation under the letter. */
  outro: string;
}

/** Language-independent: the clippings, in reading order, which side of the
 * prose they sit on, and how far each is tilted. Referenced by `slot`. */
export const STORY_CLIPPINGS = [
  { id: "proust-portrait", rotate: 1.4, side: "right", depth: 1 },
  { id: "starry-night", rotate: -1.6, side: "left", depth: 0 },
  { id: "woman-reading-letter", rotate: 1.3, side: "right", depth: 2 },
  { id: "school-of-athens", rotate: -1.2, side: "left", depth: 1 },
  { id: "almond-blossom", rotate: 1.6, side: "right", depth: 1 },
  { id: "dante-michelino", rotate: -1.4, side: "left", depth: 2 },
] as const;

export const STORY_CONTENT: Record<LegalLang, StoryCopy> = {
  en: {
    title: "The story",
    intro: "why I made this",
    blocks: [
      { type: "quote", text: "The only true voyage… would be not to visit strange lands but to possess other eyes.", cite: "Marcel Proust" },
      { type: "p", text: "I think this is partly why I have always been drawn to languages." },
      { type: "p", text: "Learning another language is not only learning another name for the same thing. Slowly, you begin to notice ==different ways of describing the world==, different rhythms, different ways of remembering, joking, thinking." },
      { type: "p", text: "And at some point, you want to go further." },
      { type: "art", slot: 0, caption: "Proust, in Blanche's portrait, 1892" },
      { type: "p", text: "You want to read the books that were written in that language. Understand a film without waiting for the subtitle. Recognise a sentence by Proust, a thought by Spinoza, or something written in a painter's letter and hear at least a little of the voice that was originally there." },
      { type: "p", text: "But when I was learning languages myself, I kept finding the same kind of material." },
      { type: "lines", lines: ["How to order something in a restaurant.", "How to introduce yourself.", "How to book a hotel room."] },
      { type: "p", text: "All useful things." },
      { type: "p", text: "But very rarely something I would have chosen to read if I weren't studying a language." },
      { type: "p", text: "That bothered me." },
      { type: "p", text: "Why should becoming a beginner in French or English suddenly mean becoming interested in things I had never cared about before?" },
      { type: "p", text: "I still wanted ==paintings, cinema, literature, philosophy==. I just needed a way into them." },
      { type: "p", text: "That was the beginning of AnyText." },
      { type: "art", slot: 1, caption: "the sky that won't settle, 1889" },
      { type: "p", text: "I wanted to take things that were already worth discovering and make the language around them accessible." },
      { type: "p", text: "Not to turn Van Gogh into a language exercise. Not to reduce a film to vocabulary practice. ==The subject should remain the reason you are there.==" },
      { type: "p", text: "The language simply becomes a little easier to enter." },
      { type: "quote", text: "A book read by a thousand different people is a thousand different books.", cite: "Andrei Tarkovsky" },
      { type: "p", text: "I love that idea." },
      { type: "p", text: "Because reading is never only about understanding every word correctly. We bring ourselves into it: what we already know, what we have lived through, what catches our attention and what passes us by." },
      { type: "p", text: "I wanted AnyText to leave room for that." },
      { type: "art", slot: 2, caption: "a letter, read slowly, c. 1663" },
      { type: "p", text: "You might open the app because you are learning French and leave having discovered a painting you had never seen before. Or save a film for later. Or come across a writer whose name stays with you." },
      { type: "p", text: "Sometimes learning the language becomes almost secondary for a moment." },
      { type: "p", text: "I think that is a good thing." },
      { type: "p", text: "The collection grew in the same way my own interests have grown over the years: through books, films, museums, friends, accidental discoveries and long evenings spent following one name into another." },
      { type: "p", text: "There is no algorithm deciding that a particular painting should be there because it is likely to perform well." },
      { type: "p", text: "==I choose things because I think they are worth someone's time.==" },
      { type: "art", slot: 3, caption: "where minds gather, 1509–1511" },
      { type: "p", text: "Sometimes because they are important. Sometimes because they are beautiful or strange. Sometimes simply because I found something and couldn't stop thinking about it." },
      { type: "quote", text: "There's nothing more genuinely artistic than to love people.", cite: "Vincent van Gogh" },
      { type: "p", text: "Van Gogh wrote that to his brother Theo in 1888." },
      { type: "art", slot: 4, caption: "almond blossom, for a newborn nephew, 1890" },
      { type: "p", text: "I like the sentence because it says something I often feel about art in general. Behind all these paintings, novels and films are people trying to make sense of being here." },
      { type: "p", text: "Maybe that is also why we keep returning to them." },
      { type: "p", text: "The technology in AnyText is meant to stay out of the way." },
      { type: "p", text: "If you don't know a word, tap it. See the meaning. Keep going." },
      { type: "p", text: "I never wanted reading to turn into a sequence of exercises." },
      { type: "p", text: "The important part is that you keep following the thought." },
      { type: "p", text: "And perhaps, little by little, you stop feeling that the language is something standing between you and the things you love." },
      { type: "p", text: "==It becomes the way you reach them.==" },
      { type: "art", slot: 5, caption: "Dante and the three kingdoms, 1465" },
      { type: "p", text: "AnyText began because I wanted that for myself." },
      { type: "p", text: "A place where learning a language could also mean discovering a filmmaker, understanding a painting a little better, meeting an old idea for the first time, or finding the next book you want to read." },
      { type: "p", text: "There is still a lot I want to add, change and improve." },
      { type: "p", text: "But that part has stayed the same from the beginning." },
      { type: "finale", lines: ["I want learning a language to lead somewhere.", "Not only to more words.", "To something worth knowing."] },
    ],
    signoff: "— Musti",
    outro: "If any of this speaks to you, today's page is waiting.",
  },
  tr: {
    title: "Hikâye",
    intro: "bunu neden yaptım",
    blocks: [
      { type: "quote", text: "Tek gerçek yolculuk… yeni topraklara gitmek değil, başka gözlere sahip olmak olurdu.", cite: "Marcel Proust" },
      { type: "p", text: "Sanırım dillere hep bu yüzden çekildim, en azından biraz." },
      { type: "p", text: "Başka bir dil öğrenmek, aynı şeye yalnızca başka bir ad vermeyi öğrenmek değildir. Yavaş yavaş ==dünyayı anlatmanın başka yollarını== fark etmeye başlarsın; başka ritimleri, hatırlamanın, şaka yapmanın, düşünmenin başka biçimlerini." },
      { type: "p", text: "Ve bir noktada daha ileri gitmek istersin." },
      { type: "art", slot: 0, caption: "Proust, Blanche'ın portresinde, 1892" },
      { type: "p", text: "O dilde yazılmış kitapları okumak istersin. Bir filmi altyazıyı beklemeden anlamak. Proust'un bir cümlesini, Spinoza'nın bir düşüncesini ya da bir ressamın mektubuna yazdığı bir şeyi tanımak ve oradaki asıl sesi, hiç değilse biraz, duymak." },
      { type: "p", text: "Ama ben dil öğrenirken hep aynı türden malzemeyle karşılaştım." },
      { type: "lines", lines: ["Restoranda nasıl sipariş verilir.", "Kendini nasıl tanıtırsın.", "Otel odası nasıl ayırtılır."] },
      { type: "p", text: "Hepsi işe yarar şeyler." },
      { type: "p", text: "Ama dil çalışmıyor olsam okumayı seçeceğim bir şeye pek nadir rastladım." },
      { type: "p", text: "Bu beni rahatsız etti." },
      { type: "p", text: "Fransızcada ya da İngilizcede yeni başlayan biri olmak, neden birdenbire daha önce hiç umursamadığım şeylerle ilgilenmek anlamına gelsin?" },
      { type: "p", text: "Ben hâlâ ==resim, sinema, edebiyat, felsefe== istiyordum. Sadece onlara giden bir yola ihtiyacım vardı." },
      { type: "p", text: "AnyText böyle başladı." },
      { type: "p", text: "Zaten keşfedilmeye değer olan şeyleri alıp etraflarındaki dili erişilebilir kılmak istedim." },
      { type: "art", slot: 1, caption: "durulmayan gökyüzü, 1889" },
      { type: "p", text: "Van Gogh'u bir dil alıştırmasına çevirmek için değil. Bir filmi kelime pratiğine indirgemek için değil. ==Orada bulunmanın sebebi konunun kendisi olarak kalmalı.==" },
      { type: "p", text: "Dil yalnızca biraz daha kolay girilir hale gelir." },
      { type: "quote", text: "Bin farklı insanın okuduğu bir kitap, bin farklı kitaptır.", cite: "Andrey Tarkovski" },
      { type: "p", text: "Bu fikri çok seviyorum." },
      { type: "p", text: "Çünkü okumak hiçbir zaman yalnızca her kelimeyi doğru anlamak değildir. Kendimizi de katarız: bildiklerimizi, yaşadıklarımızı, dikkatimizi çekeni ve gözümüzden kaçanı." },
      { type: "p", text: "AnyText'in buna yer bırakmasını istedim." },
      { type: "art", slot: 2, caption: "ağır ağır okunan bir mektup, y. 1663" },
      { type: "p", text: "Uygulamayı Fransızca öğrendiğin için açıp daha önce hiç görmediğin bir tabloyu keşfetmiş olarak çıkabilirsin. Ya da bir filmi sonrası için kaydedersin. Ya da adı aklında kalan bir yazara rastlarsın." },
      { type: "p", text: "Bazen dil öğrenmek bir an için neredeyse ikinci plana düşer." },
      { type: "p", text: "Bence bu iyi bir şey." },
      { type: "p", text: "Koleksiyon, kendi ilgi alanlarımın yıllar içinde büyüdüğü gibi büyüdü: kitaplarla, filmlerle, müzelerle, arkadaşlarla, tesadüfi keşiflerle ve bir ismin peşinden bir diğerine uzanan uzun akşamlarla." },
      { type: "p", text: "Belli bir tablonun 'iyi performans gösterebileceği' için orada olmasına karar veren bir algoritma yok." },
      { type: "p", text: "==Bir şeyi, birinin zamanına değeceğini düşündüğüm için seçiyorum.==" },
      { type: "art", slot: 3, caption: "zihinlerin buluştuğu yer, 1509–1511" },
      { type: "p", text: "Bazen önemli olduğu için. Bazen güzel ya da tuhaf olduğu için. Bazen de sadece bir şey bulduğum ve aklımdan çıkaramadığım için." },
      { type: "quote", text: "İnsanları sevmekten daha gerçek anlamda sanatsal hiçbir şey yoktur.", cite: "Vincent van Gogh" },
      { type: "p", text: "Van Gogh bunu 1888'de kardeşi Theo'ya yazmış." },
      { type: "art", slot: 4, caption: "yeni doğan yeğene badem çiçeği, 1890" },
      { type: "p", text: "Bu cümleyi seviyorum çünkü sanat hakkında sık sık hissettiğim bir şeyi söylüyor. Bütün bu tabloların, romanların ve filmlerin arkasında burada olmayı anlamlandırmaya çalışan insanlar var." },
      { type: "p", text: "Belki onlara hep geri dönmemizin sebebi de bu." },
      { type: "p", text: "AnyText'teki teknoloji aradan çekilmek için var." },
      { type: "p", text: "Bir kelimeyi bilmiyorsan dokun. Anlamına bak. Devam et." },
      { type: "p", text: "Okumanın bir alıştırmalar dizisine dönüşmesini hiç istemedim." },
      { type: "p", text: "Önemli olan düşüncenin peşinden gitmeye devam etmen." },
      { type: "p", text: "Ve belki yavaş yavaş, dilin seninle sevdiğin şeyler arasında duran bir engel olduğu hissi geçer." },
      { type: "p", text: "==Dil, onlara ulaşma yolun olur.==" },
      { type: "art", slot: 5, caption: "Dante ve üç krallık, 1465" },
      { type: "p", text: "AnyText, bunu kendim için istediğim için başladı." },
      { type: "p", text: "Dil öğrenmenin aynı zamanda bir yönetmeni keşfetmek, bir tabloyu biraz daha iyi anlamak, eski bir fikirle ilk kez karşılaşmak ya da okumak istediğin bir sonraki kitabı bulmak anlamına da gelebildiği bir yer." },
      { type: "p", text: "Eklemek, değiştirmek ve iyileştirmek istediğim daha çok şey var." },
      { type: "p", text: "Ama şu kısım en baştan beri aynı kaldı." },
      { type: "finale", lines: ["Dil öğrenmenin bir yere götürmesini istiyorum.", "Yalnızca daha çok kelimeye değil.", "Bilmeye değer bir şeye."] },
    ],
    signoff: "— Musti",
    outro: "Bunlardan biri sana bir şey söylüyorsa, bugünün sayfası seni bekliyor.",
  },
  fr: {
    title: "L'histoire",
    intro: "pourquoi j'ai fait ça",
    blocks: [
      { type: "quote", text: "Le seul véritable voyage… ce ne serait pas d'aller vers de nouveaux paysages, mais d'avoir d'autres yeux.", cite: "Marcel Proust" },
      { type: "p", text: "Je crois que c'est en partie pour cela que les langues m'ont toujours attiré." },
      { type: "p", text: "Apprendre une autre langue, ce n'est pas seulement apprendre un autre nom pour la même chose. Peu à peu, on se met à remarquer ==d'autres façons de décrire le monde==, d'autres rythmes, d'autres manières de se souvenir, de plaisanter, de penser." },
      { type: "p", text: "Et à un moment donné, on a envie d'aller plus loin." },
      { type: "art", slot: 0, caption: "Proust, par Blanche, 1892" },
      { type: "p", text: "On veut lire les livres écrits dans cette langue. Comprendre un film sans attendre le sous-titre. Reconnaître une phrase de Proust, une pensée de Spinoza, ou quelques mots tirés de la lettre d'un peintre, et entendre, ne serait-ce qu'un peu, la voix qui était là au départ." },
      { type: "p", text: "Mais quand j'apprenais des langues moi-même, je retombais toujours sur le même genre de matériel." },
      { type: "lines", lines: ["Comment commander au restaurant.", "Comment se présenter.", "Comment réserver une chambre d'hôtel."] },
      { type: "p", text: "Toutes choses utiles." },
      { type: "p", text: "Mais très rarement quelque chose que j'aurais choisi de lire si je n'avais pas été en train d'étudier une langue." },
      { type: "p", text: "Cela me dérangeait." },
      { type: "p", text: "Pourquoi devenir débutant en français ou en anglais devrait-il soudain signifier s'intéresser à des choses dont je ne m'étais jamais soucié ?" },
      { type: "p", text: "Je voulais toujours ==la peinture, le cinéma, la littérature, la philosophie==. Il me fallait simplement un chemin pour y entrer." },
      { type: "p", text: "C'est ainsi qu'AnyText a commencé." },
      { type: "p", text: "Je voulais prendre des choses qui valaient déjà la peine d'être découvertes et rendre accessible la langue qui les entoure." },
      { type: "art", slot: 1, caption: "le ciel qui ne se calme pas, 1889" },
      { type: "p", text: "Pas pour transformer Van Gogh en exercice de langue. Pas pour réduire un film à de la pratique de vocabulaire. ==Le sujet doit rester la raison pour laquelle on est là.==" },
      { type: "p", text: "La langue devient simplement un peu plus facile à aborder." },
      { type: "quote", text: "Un livre lu par mille personnes différentes, c'est mille livres différents.", cite: "Andreï Tarkovski" },
      { type: "p", text: "J'adore cette idée." },
      { type: "p", text: "Parce que lire, ce n'est jamais seulement comprendre chaque mot correctement. On s'y met soi-même : ce qu'on sait déjà, ce qu'on a vécu, ce qui retient notre attention et ce qui nous échappe." },
      { type: "p", text: "Je voulais qu'AnyText laisse de la place à cela." },
      { type: "art", slot: 2, caption: "une lettre, lue lentement, v. 1663" },
      { type: "p", text: "On peut ouvrir l'application parce qu'on apprend le français et en ressortir en ayant découvert un tableau qu'on n'avait jamais vu. Ou mettre un film de côté pour plus tard. Ou tomber sur un écrivain dont le nom nous reste." },
      { type: "p", text: "Parfois, apprendre la langue devient presque secondaire, le temps d'un instant." },
      { type: "p", text: "Je trouve que c'est une bonne chose." },
      { type: "p", text: "La collection a grandi comme mes propres goûts ont grandi au fil des années : par les livres, les films, les musées, les amis, les découvertes accidentelles et les longues soirées passées à suivre un nom jusqu'au suivant." },
      { type: "p", text: "Aucun algorithme ne décide qu'un tableau doit être là parce qu'il a des chances de « bien marcher »." },
      { type: "p", text: "==Je choisis les choses parce que je pense qu'elles valent le temps de quelqu'un.==" },
      { type: "art", slot: 3, caption: "là où les esprits se rencontrent, 1509–1511" },
      { type: "p", text: "Parfois parce qu'elles sont importantes. Parfois parce qu'elles sont belles ou étranges. Parfois simplement parce que j'ai trouvé quelque chose et que je n'ai pas pu m'empêcher d'y repenser." },
      { type: "quote", text: "Il n'y a rien de plus véritablement artistique que d'aimer les gens.", cite: "Vincent van Gogh" },
      { type: "p", text: "Van Gogh l'a écrit à son frère Theo en 1888." },
      { type: "art", slot: 4, caption: "des amandiers en fleurs, pour un neveu nouveau-né, 1890" },
      { type: "p", text: "J'aime cette phrase parce qu'elle dit quelque chose que je ressens souvent à propos de l'art en général. Derrière tous ces tableaux, ces romans et ces films, il y a des gens qui essaient de donner un sens au fait d'être ici." },
      { type: "p", text: "C'est peut-être aussi pour cela qu'on y revient sans cesse." },
      { type: "p", text: "La technologie, dans AnyText, est faite pour rester en retrait." },
      { type: "p", text: "Un mot inconnu ? On le touche. On voit le sens. On continue." },
      { type: "p", text: "Je n'ai jamais voulu que la lecture se transforme en une suite d'exercices." },
      { type: "p", text: "L'important, c'est de continuer à suivre la pensée." },
      { type: "p", text: "Et peut-être que, petit à petit, on cesse de sentir que la langue est quelque chose qui se dresse entre soi et ce qu'on aime." },
      { type: "p", text: "==Elle devient le chemin par lequel on y arrive.==" },
      { type: "art", slot: 5, caption: "Dante et les trois royaumes, 1465" },
      { type: "p", text: "AnyText est né parce que je voulais cela pour moi-même." },
      { type: "p", text: "Un endroit où apprendre une langue peut aussi vouloir dire découvrir un cinéaste, comprendre un peu mieux un tableau, rencontrer une vieille idée pour la première fois, ou trouver le prochain livre qu'on a envie de lire." },
      { type: "p", text: "Il reste beaucoup de choses que je veux ajouter, changer et améliorer." },
      { type: "p", text: "Mais cette part-là n'a pas bougé depuis le début." },
      { type: "finale", lines: ["Je veux qu'apprendre une langue mène quelque part.", "Pas seulement à plus de mots.", "À quelque chose qui vaut la peine d'être connu."] },
    ],
    signoff: "— Musti",
    outro: "Si quelque chose ici vous parle, la page du jour vous attend.",
  },
  it: {
    title: "La storia",
    intro: "perché l'ho fatto",
    blocks: [
      { type: "quote", text: "L'unico vero viaggio… non sarebbe andare verso nuovi paesaggi, ma avere altri occhi.", cite: "Marcel Proust" },
      { type: "p", text: "Credo sia in parte per questo che le lingue mi hanno sempre attratto." },
      { type: "p", text: "Imparare un'altra lingua non è soltanto imparare un altro nome per la stessa cosa. Piano piano cominci a notare ==altri modi di descrivere il mondo==, altri ritmi, altri modi di ricordare, di scherzare, di pensare." },
      { type: "p", text: "E a un certo punto vuoi andare oltre." },
      { type: "art", slot: 0, caption: "Proust, nel ritratto di Blanche, 1892" },
      { type: "p", text: "Vuoi leggere i libri scritti in quella lingua. Capire un film senza aspettare il sottotitolo. Riconoscere una frase di Proust, un pensiero di Spinoza o qualcosa scritto nella lettera di un pittore, e sentire almeno un po' la voce che c'era in origine." },
      { type: "p", text: "Ma quando imparavo le lingue io stesso, trovavo sempre lo stesso tipo di materiale." },
      { type: "lines", lines: ["Come ordinare al ristorante.", "Come presentarsi.", "Come prenotare una camera d'albergo."] },
      { type: "p", text: "Tutte cose utili." },
      { type: "p", text: "Ma molto raramente qualcosa che avrei scelto di leggere se non avessi studiato una lingua." },
      { type: "p", text: "Questo mi dava fastidio." },
      { type: "p", text: "Perché diventare un principiante in francese o in inglese dovrebbe all'improvviso significare interessarsi a cose di cui non mi era mai importato nulla?" },
      { type: "p", text: "Volevo ancora ==la pittura, il cinema, la letteratura, la filosofia==. Mi serviva solo una via per entrarci." },
      { type: "p", text: "Così è iniziato AnyText." },
      { type: "p", text: "Volevo prendere cose che già valeva la pena scoprire e rendere accessibile la lingua che le circonda." },
      { type: "art", slot: 1, caption: "il cielo che non si posa, 1889" },
      { type: "p", text: "Non per trasformare Van Gogh in un esercizio di lingua. Non per ridurre un film a pratica di vocabolario. ==Il soggetto deve restare il motivo per cui sei lì.==" },
      { type: "p", text: "La lingua diventa semplicemente un po' più facile da attraversare." },
      { type: "quote", text: "Un libro letto da mille persone diverse è mille libri diversi.", cite: "Andrej Tarkovskij" },
      { type: "p", text: "Adoro questa idea." },
      { type: "p", text: "Perché leggere non è mai soltanto capire correttamente ogni parola. Ci mettiamo noi stessi: quello che già sappiamo, quello che abbiamo vissuto, ciò che cattura la nostra attenzione e ciò che ci sfugge." },
      { type: "p", text: "Volevo che AnyText lasciasse spazio a questo." },
      { type: "art", slot: 2, caption: "una lettera, letta lentamente, 1663 ca." },
      { type: "p", text: "Puoi aprire l'app perché stai imparando il francese e uscirne avendo scoperto un quadro che non avevi mai visto. O salvare un film per dopo. O imbatterti in uno scrittore il cui nome ti resta addosso." },
      { type: "p", text: "A volte imparare la lingua diventa quasi secondario, per un momento." },
      { type: "p", text: "Credo che sia una cosa buona." },
      { type: "p", text: "La collezione è cresciuta come sono cresciuti i miei interessi negli anni: attraverso libri, film, musei, amici, scoperte casuali e lunghe serate passate a seguire un nome dentro un altro." },
      { type: "p", text: "Non c'è nessun algoritmo a decidere che un certo quadro debba esserci perché probabilmente « funzionerà »." },
      { type: "p", text: "==Scelgo le cose perché penso che valgano il tempo di qualcuno.==" },
      { type: "art", slot: 3, caption: "dove si incontrano le menti, 1509–1511" },
      { type: "p", text: "A volte perché sono importanti. A volte perché sono belle o strane. A volte semplicemente perché ho trovato qualcosa e non ho più smesso di pensarci." },
      { type: "quote", text: "Non c'è nulla di più autenticamente artistico che amare le persone.", cite: "Vincent van Gogh" },
      { type: "p", text: "Van Gogh lo scrisse al fratello Theo nel 1888." },
      { type: "art", slot: 4, caption: "mandorlo in fiore, per un nipote appena nato, 1890" },
      { type: "p", text: "Amo questa frase perché dice qualcosa che sento spesso a proposito dell'arte in generale. Dietro tutti questi quadri, romanzi e film ci sono persone che cercano di dare un senso all'essere qui." },
      { type: "p", text: "Forse è anche per questo che continuiamo a tornarci." },
      { type: "p", text: "La tecnologia di AnyText è fatta per restare in disparte." },
      { type: "p", text: "Se non conosci una parola, toccala. Guarda il significato. Vai avanti." },
      { type: "p", text: "Non ho mai voluto che la lettura diventasse una sequenza di esercizi." },
      { type: "p", text: "L'importante è continuare a seguire il pensiero." },
      { type: "p", text: "E forse, poco a poco, smetti di sentire che la lingua sia qualcosa che si frappone tra te e le cose che ami." },
      { type: "p", text: "==Diventa il modo in cui le raggiungi.==" },
      { type: "art", slot: 5, caption: "Dante e i tre regni, 1465" },
      { type: "p", text: "AnyText è nato perché volevo questo per me stesso." },
      { type: "p", text: "Un posto in cui imparare una lingua possa anche voler dire scoprire un regista, capire un po' meglio un quadro, incontrare per la prima volta un'idea antica o trovare il prossimo libro che vuoi leggere." },
      { type: "p", text: "C'è ancora molto che voglio aggiungere, cambiare e migliorare." },
      { type: "p", text: "Ma quella parte è rimasta la stessa dall'inizio." },
      { type: "finale", lines: ["Voglio che imparare una lingua porti da qualche parte.", "Non solo a più parole.", "A qualcosa che vale la pena conoscere."] },
    ],
    signoff: "— Musti",
    outro: "Se qualcosa di tutto questo ti parla, la pagina di oggi ti aspetta.",
  },
  es: {
    title: "La historia",
    intro: "por qué hice esto",
    blocks: [
      { type: "quote", text: "El único verdadero viaje… no sería ir hacia nuevos paisajes, sino tener otros ojos.", cite: "Marcel Proust" },
      { type: "p", text: "Creo que en parte por eso siempre me han atraído los idiomas." },
      { type: "p", text: "Aprender otro idioma no es solo aprender otro nombre para la misma cosa. Poco a poco empiezas a notar ==otras maneras de describir el mundo==, otros ritmos, otras formas de recordar, de bromear, de pensar." },
      { type: "p", text: "Y en algún momento quieres ir más lejos." },
      { type: "art", slot: 0, caption: "Proust, en el retrato de Blanche, 1892" },
      { type: "p", text: "Quieres leer los libros que se escribieron en ese idioma. Entender una película sin esperar al subtítulo. Reconocer una frase de Proust, un pensamiento de Spinoza o algo escrito en la carta de un pintor, y oír, aunque sea un poco, la voz que estaba ahí desde el principio." },
      { type: "p", text: "Pero cuando yo mismo aprendía idiomas, me encontraba siempre con el mismo tipo de material." },
      { type: "lines", lines: ["Cómo pedir algo en un restaurante.", "Cómo presentarte.", "Cómo reservar una habitación de hotel."] },
      { type: "p", text: "Todo cosas útiles." },
      { type: "p", text: "Pero muy pocas veces algo que yo hubiera elegido leer si no estuviera estudiando un idioma." },
      { type: "p", text: "Eso me molestaba." },
      { type: "p", text: "¿Por qué convertirme en principiante de francés o de inglés tendría que significar, de repente, interesarme por cosas que nunca me habían importado?" },
      { type: "p", text: "Yo seguía queriendo ==pintura, cine, literatura, filosofía==. Solo necesitaba una manera de entrar en ellas." },
      { type: "p", text: "Así empezó AnyText." },
      { type: "p", text: "Quería tomar cosas que ya merecían ser descubiertas y hacer accesible el idioma que las rodea." },
      { type: "art", slot: 1, caption: "el cielo que no se aquieta, 1889" },
      { type: "p", text: "No para convertir a Van Gogh en un ejercicio de idiomas. No para reducir una película a práctica de vocabulario. ==El tema debe seguir siendo la razón por la que estás ahí.==" },
      { type: "p", text: "El idioma, sencillamente, se vuelve un poco más fácil de atravesar." },
      { type: "quote", text: "Un libro leído por mil personas distintas son mil libros distintos.", cite: "Andréi Tarkovski" },
      { type: "p", text: "Me encanta esa idea." },
      { type: "p", text: "Porque leer nunca es solo entender correctamente cada palabra. Nos ponemos a nosotros mismos en ello: lo que ya sabemos, lo que hemos vivido, lo que nos llama la atención y lo que se nos escapa." },
      { type: "p", text: "Quería que AnyText dejara espacio para eso." },
      { type: "art", slot: 2, caption: "una carta, leída despacio, c. 1663" },
      { type: "p", text: "Puedes abrir la app porque estás aprendiendo francés y salir habiendo descubierto un cuadro que nunca habías visto. O guardar una película para más tarde. O toparte con un escritor cuyo nombre se te queda." },
      { type: "p", text: "A veces, por un momento, aprender el idioma pasa casi a segundo plano." },
      { type: "p", text: "Creo que eso es bueno." },
      { type: "p", text: "La colección creció como han crecido mis propios intereses a lo largo de los años: con libros, películas, museos, amigos, descubrimientos casuales y largas tardes siguiendo un nombre hasta el siguiente." },
      { type: "p", text: "No hay ningún algoritmo que decida que un cuadro debe estar ahí porque probablemente « funcione bien »." },
      { type: "p", text: "==Elijo las cosas porque creo que merecen el tiempo de alguien.==" },
      { type: "art", slot: 3, caption: "donde se reúnen las mentes, 1509–1511" },
      { type: "p", text: "A veces porque son importantes. A veces porque son bellas o extrañas. A veces, simplemente, porque encontré algo y no pude dejar de pensar en ello." },
      { type: "quote", text: "No hay nada más genuinamente artístico que amar a la gente.", cite: "Vincent van Gogh" },
      { type: "p", text: "Van Gogh se lo escribió a su hermano Theo en 1888." },
      { type: "art", slot: 4, caption: "almendro en flor, para un sobrino recién nacido, 1890" },
      { type: "p", text: "Me gusta la frase porque dice algo que a menudo siento sobre el arte en general. Detrás de todos estos cuadros, novelas y películas hay personas intentando dar sentido al hecho de estar aquí." },
      { type: "p", text: "Quizá también por eso volvemos a ellos una y otra vez." },
      { type: "p", text: "La tecnología de AnyText está hecha para no estorbar." },
      { type: "p", text: "Si no conoces una palabra, tócala. Mira lo que significa. Sigue leyendo." },
      { type: "p", text: "Nunca quise que la lectura se convirtiera en una secuencia de ejercicios." },
      { type: "p", text: "Lo importante es que sigas el hilo del pensamiento." },
      { type: "p", text: "Y quizá, poco a poco, dejes de sentir que el idioma es algo que se interpone entre tú y lo que amas." },
      { type: "p", text: "==Se convierte en el camino para llegar a ello.==" },
      { type: "art", slot: 5, caption: "Dante y los tres reinos, 1465" },
      { type: "p", text: "AnyText empezó porque yo quería eso para mí." },
      { type: "p", text: "Un lugar donde aprender un idioma pueda significar también descubrir a un cineasta, entender un poco mejor un cuadro, encontrarse por primera vez con una idea antigua o dar con el próximo libro que quieres leer." },
      { type: "p", text: "Todavía hay mucho que quiero añadir, cambiar y mejorar." },
      { type: "p", text: "Pero esa parte no ha cambiado desde el principio." },
      { type: "finale", lines: ["Quiero que aprender un idioma lleve a alguna parte.", "No solo a más palabras.", "A algo que merezca la pena conocer."] },
    ],
    signoff: "— Musti",
    outro: "Si algo de esto te dice algo, la página de hoy te espera.",
  },
  de: {
    title: "Die Geschichte",
    intro: "warum ich das gemacht habe",
    blocks: [
      { type: "quote", text: "Die einzige wahre Reise… wäre nicht, neue Landschaften aufzusuchen, sondern andere Augen zu haben.", cite: "Marcel Proust" },
      { type: "p", text: "Ich glaube, das ist zum Teil der Grund, warum mich Sprachen immer angezogen haben." },
      { type: "p", text: "Eine andere Sprache zu lernen heißt nicht nur, einen anderen Namen für dieselbe Sache zu lernen. Nach und nach fallen einem ==andere Arten auf, die Welt zu beschreiben==, andere Rhythmen, andere Arten, sich zu erinnern, zu scherzen, zu denken." },
      { type: "p", text: "Und irgendwann will man weiter." },
      { type: "art", slot: 0, caption: "Proust, in Blanches Porträt, 1892" },
      { type: "p", text: "Man will die Bücher lesen, die in dieser Sprache geschrieben wurden. Einen Film verstehen, ohne auf den Untertitel zu warten. Einen Satz von Proust wiedererkennen, einen Gedanken von Spinoza oder etwas aus dem Brief eines Malers – und wenigstens ein wenig von der Stimme hören, die ursprünglich da war." },
      { type: "p", text: "Aber als ich selbst Sprachen lernte, stieß ich immer wieder auf dieselbe Art von Material." },
      { type: "lines", lines: ["Wie man im Restaurant bestellt.", "Wie man sich vorstellt.", "Wie man ein Hotelzimmer bucht."] },
      { type: "p", text: "Alles nützliche Dinge." },
      { type: "p", text: "Aber nur sehr selten etwas, das ich gelesen hätte, wenn ich nicht gerade eine Sprache gelernt hätte." },
      { type: "p", text: "Das hat mich gestört." },
      { type: "p", text: "Warum sollte es, wenn man Anfänger in Französisch oder Englisch wird, plötzlich bedeuten, sich für Dinge zu interessieren, die einen nie interessiert haben?" },
      { type: "p", text: "Ich wollte nach wie vor ==Malerei, Kino, Literatur, Philosophie==. Ich brauchte nur einen Weg hinein." },
      { type: "p", text: "So hat AnyText angefangen." },
      { type: "p", text: "Ich wollte Dinge nehmen, die ohnehin entdeckt zu werden verdienen, und die Sprache um sie herum zugänglich machen." },
      { type: "art", slot: 1, caption: "der Himmel, der nicht zur Ruhe kommt, 1889" },
      { type: "p", text: "Nicht, um Van Gogh in eine Sprachübung zu verwandeln. Nicht, um einen Film auf Vokabeltraining zu reduzieren. ==Das Thema soll der Grund bleiben, warum man da ist.==" },
      { type: "p", text: "Die Sprache wird einfach ein wenig leichter zugänglich." },
      { type: "quote", text: "Ein Buch, das von tausend verschiedenen Menschen gelesen wird, ist tausend verschiedene Bücher.", cite: "Andrei Tarkowski" },
      { type: "p", text: "Ich liebe diesen Gedanken." },
      { type: "p", text: "Denn Lesen heißt nie nur, jedes Wort richtig zu verstehen. Wir bringen uns selbst mit hinein: was wir schon wissen, was wir erlebt haben, was unsere Aufmerksamkeit fängt und was an uns vorbeigeht." },
      { type: "p", text: "Ich wollte, dass AnyText dafür Raum lässt." },
      { type: "art", slot: 2, caption: "ein Brief, langsam gelesen, um 1663" },
      { type: "p", text: "Man öffnet die App vielleicht, weil man Französisch lernt, und geht mit einem Gemälde hinaus, das man noch nie gesehen hatte. Oder merkt sich einen Film für später. Oder stößt auf einen Schriftsteller, dessen Name einen nicht mehr loslässt." },
      { type: "p", text: "Manchmal wird das Sprachenlernen für einen Moment fast zur Nebensache." },
      { type: "p", text: "Ich finde, das ist gut so." },
      { type: "p", text: "Die Sammlung ist so gewachsen, wie meine eigenen Interessen über die Jahre gewachsen sind: durch Bücher, Filme, Museen, Freunde, zufällige Entdeckungen und lange Abende, an denen ein Name zum nächsten führte." },
      { type: "p", text: "Kein Algorithmus entscheidet, dass ein bestimmtes Gemälde da sein soll, weil es wahrscheinlich „gut ankommt“." },
      { type: "p", text: "==Ich wähle Dinge aus, weil ich glaube, dass sie jemandes Zeit wert sind.==" },
      { type: "art", slot: 3, caption: "wo die Köpfe zusammenkommen, 1509–1511" },
      { type: "p", text: "Manchmal, weil sie wichtig sind. Manchmal, weil sie schön oder seltsam sind. Manchmal einfach, weil ich etwas gefunden habe und nicht aufhören konnte, daran zu denken." },
      { type: "quote", text: "Es gibt nichts wahrhaft Künstlerischeres, als Menschen zu lieben.", cite: "Vincent van Gogh" },
      { type: "p", text: "Van Gogh schrieb das 1888 an seinen Bruder Theo." },
      { type: "art", slot: 4, caption: "Mandelblüte, für einen neugeborenen Neffen, 1890" },
      { type: "p", text: "Ich mag den Satz, weil er etwas ausspricht, das ich über Kunst im Allgemeinen oft empfinde. Hinter all diesen Gemälden, Romanen und Filmen stehen Menschen, die versuchen, dem Hiersein einen Sinn zu geben." },
      { type: "p", text: "Vielleicht ist das auch der Grund, warum wir immer wieder zu ihnen zurückkehren." },
      { type: "p", text: "Die Technik in AnyText soll im Hintergrund bleiben." },
      { type: "p", text: "Kennst du ein Wort nicht, tippst du es an. Siehst die Bedeutung. Liest weiter." },
      { type: "p", text: "Ich wollte nie, dass Lesen zu einer Abfolge von Übungen wird." },
      { type: "p", text: "Wichtig ist, dass man dem Gedanken weiter folgt." },
      { type: "p", text: "Und vielleicht hört man nach und nach auf, die Sprache als etwas zu empfinden, das zwischen einem selbst und den Dingen steht, die man liebt." },
      { type: "p", text: "==Sie wird zum Weg, auf dem man sie erreicht.==" },
      { type: "art", slot: 5, caption: "Dante und die drei Reiche, 1465" },
      { type: "p", text: "AnyText hat angefangen, weil ich das für mich selbst wollte." },
      { type: "p", text: "Einen Ort, an dem eine Sprache zu lernen auch heißen kann, einen Filmemacher zu entdecken, ein Gemälde ein wenig besser zu verstehen, einer alten Idee zum ersten Mal zu begegnen oder das nächste Buch zu finden, das man lesen möchte." },
      { type: "p", text: "Es gibt noch vieles, das ich hinzufügen, ändern und verbessern will." },
      { type: "p", text: "Aber dieser Teil ist von Anfang an gleich geblieben." },
      { type: "finale", lines: ["Ich möchte, dass Sprachenlernen irgendwohin führt.", "Nicht nur zu mehr Wörtern.", "Zu etwas, das es wert ist, gewusst zu werden."] },
    ],
    signoff: "— Musti",
    outro: "Wenn dich etwas davon anspricht: Die Seite von heute wartet.",
  },
  nl: {
    title: "Het verhaal",
    intro: "waarom ik dit heb gemaakt",
    blocks: [
      { type: "quote", text: "De enige echte reis… zou niet zijn om vreemde landen te bezoeken, maar om andere ogen te hebben.", cite: "Marcel Proust" },
      { type: "p", text: "Ik denk dat dit deels de reden is waarom talen me altijd hebben aangetrokken." },
      { type: "p", text: "Een andere taal leren is niet alleen een andere naam leren voor hetzelfde ding. Langzaam begin je ==andere manieren op te merken om de wereld te beschrijven==, andere ritmes, andere manieren van herinneren, grappen maken, denken." },
      { type: "p", text: "En op een gegeven moment wil je verder." },
      { type: "art", slot: 0, caption: "Proust, in het portret van Blanche, 1892" },
      { type: "p", text: "Je wilt de boeken lezen die in die taal geschreven zijn. Een film begrijpen zonder op de ondertitel te wachten. Een zin van Proust herkennen, een gedachte van Spinoza, of iets uit een brief van een schilder – en tenminste een beetje van de stem horen die er oorspronkelijk was." },
      { type: "p", text: "Maar toen ik zelf talen leerde, kwam ik steeds hetzelfde soort materiaal tegen." },
      { type: "lines", lines: ["Hoe je iets bestelt in een restaurant.", "Hoe je jezelf voorstelt.", "Hoe je een hotelkamer boekt."] },
      { type: "p", text: "Allemaal nuttige dingen." },
      { type: "p", text: "Maar zelden iets wat ik gekozen zou hebben om te lezen als ik geen taal aan het leren was." },
      { type: "p", text: "Dat stoorde me." },
      { type: "p", text: "Waarom zou beginner worden in het Frans of Engels ineens betekenen dat je geïnteresseerd raakt in dingen waar je nooit om gaf?" },
      { type: "p", text: "Ik wilde nog steeds ==schilderkunst, film, literatuur, filosofie==. Ik had alleen een ingang nodig." },
      { type: "p", text: "Zo begon AnyText." },
      { type: "p", text: "Ik wilde dingen nemen die het al waard waren om ontdekt te worden, en de taal eromheen toegankelijk maken." },
      { type: "art", slot: 1, caption: "de lucht die niet tot rust komt, 1889" },
      { type: "p", text: "Niet om Van Gogh in een taaloefening te veranderen. Niet om een film terug te brengen tot woordenschattraining. ==Het onderwerp moet de reden blijven waarom je er bent.==" },
      { type: "p", text: "De taal wordt gewoon een beetje makkelijker om binnen te komen." },
      { type: "quote", text: "Een boek dat door duizend verschillende mensen wordt gelezen, is duizend verschillende boeken.", cite: "Andrej Tarkovski" },
      { type: "p", text: "Ik hou van dat idee." },
      { type: "p", text: "Want lezen is nooit alleen elk woord correct begrijpen. We brengen onszelf mee: wat we al weten, wat we hebben meegemaakt, wat onze aandacht trekt en wat ons ontgaat." },
      { type: "p", text: "Ik wilde dat AnyText daar ruimte voor liet." },
      { type: "art", slot: 2, caption: "een brief, langzaam gelezen, ca. 1663" },
      { type: "p", text: "Je opent de app misschien omdat je Frans leert, en je sluit hem af met een schilderij dat je nog nooit had gezien. Of je bewaart een film voor later. Of je stuit op een schrijver van wie de naam blijft hangen." },
      { type: "p", text: "Soms wordt de taal leren even bijna bijzaak." },
      { type: "p", text: "Ik vind dat een goede zaak." },
      { type: "p", text: "De collectie is gegroeid zoals mijn eigen interesses door de jaren heen zijn gegroeid: via boeken, films, musea, vrienden, toevallige ontdekkingen en lange avonden waarin de ene naam naar de andere leidde." },
      { type: "p", text: "Er is geen algoritme dat bepaalt dat een bepaald schilderij erbij moet omdat het waarschijnlijk „goed scoort”." },
      { type: "p", text: "==Ik kies dingen omdat ik denk dat ze iemands tijd waard zijn.==" },
      { type: "art", slot: 3, caption: "waar de geesten samenkomen, 1509–1511" },
      { type: "p", text: "Soms omdat ze belangrijk zijn. Soms omdat ze mooi of vreemd zijn. Soms gewoon omdat ik iets vond en er niet meer mee kon stoppen eraan te denken." },
      { type: "quote", text: "Er is niets wezenlijk kunstzinnigers dan van mensen houden.", cite: "Vincent van Gogh" },
      { type: "p", text: "Van Gogh schreef dat in 1888 aan zijn broer Theo." },
      { type: "art", slot: 4, caption: "amandelbloesem, voor een pasgeboren neefje, 1890" },
      { type: "p", text: "Ik hou van die zin omdat hij iets zegt wat ik vaak voel over kunst in het algemeen. Achter al die schilderijen, romans en films zitten mensen die proberen te begrijpen wat het is om hier te zijn." },
      { type: "p", text: "Misschien is dat ook waarom we er steeds naar terugkeren." },
      { type: "p", text: "De technologie in AnyText hoort op de achtergrond te blijven." },
      { type: "p", text: "Ken je een woord niet? Tik erop. Bekijk de betekenis. Lees verder." },
      { type: "p", text: "Ik heb nooit gewild dat lezen een reeks oefeningen zou worden." },
      { type: "p", text: "Het belangrijkste is dat je de gedachte blijft volgen." },
      { type: "p", text: "En misschien houd je, beetje bij beetje, op met het gevoel dat de taal iets is dat tussen jou en de dingen staat waar je van houdt." },
      { type: "p", text: "==Ze wordt de weg waarlangs je ze bereikt.==" },
      { type: "art", slot: 5, caption: "Dante en de drie rijken, 1465" },
      { type: "p", text: "AnyText is begonnen omdat ik dat voor mezelf wilde." },
      { type: "p", text: "Een plek waar een taal leren ook kan betekenen: een filmmaker ontdekken, een schilderij iets beter begrijpen, een oud idee voor het eerst tegenkomen, of het volgende boek vinden dat je wilt lezen." },
      { type: "p", text: "Er is nog veel dat ik wil toevoegen, veranderen en verbeteren." },
      { type: "p", text: "Maar dat deel is vanaf het begin hetzelfde gebleven." },
      { type: "finale", lines: ["Ik wil dat een taal leren ergens toe leidt.", "Niet alleen tot meer woorden.", "Tot iets wat het waard is om te weten."] },
    ],
    signoff: "— Musti",
    outro: "Als iets hiervan je aanspreekt: de pagina van vandaag wacht.",
  },
};
